---
name: Release Please

on:
  pull_request:
    types: [closed]
    branches:
      - release-*.*.*
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.SANDBOX_RELEASE_TOKEN }}
          release-type: simple
          target-branch: ${{ github.ref_name }}
